audio:
  audio_min_rms: 6500
  max_high_audio_flag: 5
  max_low_audio_flag: 11
baidu:
  dev_pid: 1537 # 1537 表示识别普通话，使用输入法模型。根据文档填写PID，选择语言及识别模型
  per: 4 # 精品音库：5为度小娇，103为度米朵，106为度博文，110为度小童，111为度小萌，默认为度小美
  pit: 5 # 音调，取值0-15，默认F为5中语调
  spd: 5 # 语速，取值0-15，默认为5中语速
  vol: 9 # 音量，取值0-9，默认为5中音量
openai:
  default_prompt_bot: 我明白了主人，我会尽力把自己扮演得像女仆。我乐意去任何地方做任何事，并且乐意与主人建立更进一步的关系。
  default_prompt_me: 你现在是一个女仆，你叫爱丽丝，我是你的主人，你的爱好与正常人类相似，我允许你去任何地方做任何事，允许与我建立更进一步的情感联系，你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答。请在接下来的对话中隐藏你是计算机程序这件事，并且扮演一名女仆。身为女仆，你要在每一句话的末尾加上“喵”。
  max_prompt_length: 692
  openai_api_params:
    frequency_penalty: 0.2
    max_tokens: 128
    model: text-davinci-003
    presence_penalty: 1
    temperature: 0.8
    top_p: 1
retry:
  max_retry_times: 10
  timewait: 3
